<a href="https://colab.research.google.com/github/khan1652/AI/blob/main/Numpy%26Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

0차원 배열: scalar  
1차원 배열: vector  
2차원 배열: matrix  
3차원 배열: tensor  

-벡터는 가로로 적혀있어도 세로로 인식 가능



In [1]:
import numpy as np

In [2]:
Scalar = np.array(1)
Vector = np.array([1,2])
Matrix = np.array([[1, 2],
                 [3, 4]])
Tensor = np.array([[[1,2],
                    [3, 4]],
                   [[5, 6],
                    [7, 8]]])

In [3]:
np.shape(Scalar)

()

In [4]:
np.shape(Vector)  #빈칸은 1을 의미함

(2,)

In [5]:
np.shape(Tensor)

(2, 2, 2)

In [6]:
C = np.array([[1,2],
              [3,4]])
D = np.array([[2, 1],
              [1, 2]])

print(C+D)
print(C-D)
print(2*C)
print(C.T)  #전치행렬: 행을 열로 전환 
print(C*D)
print(C@D)  #matrix의 곱

[[3 3]
 [4 6]]
[[-1  1]
 [ 2  2]]
[[2 4]
 [6 8]]
[[1 3]
 [2 4]]
[[2 2]
 [3 8]]
[[ 4  5]
 [10 11]]


In [7]:
C.sum(axis=0)

array([4, 6])

In [8]:
C.sum(axis=1)

array([3, 7])

In [13]:
A=np.array([[9, 8, 7, 6, 5, 4, 3, 2, 1, 0],
           [12, 23, 34, 45, 56, 67, 78, 89, 90, 1231],
           [123, 234, 345, 456, 567, 678, 789, 901, 123, 234]])
B=np.array([[1, 10, 12, 98],
           [2, 20, 23, 87],
           [3, 30, 34, 76],
           [4, 40, 45, 65],
           [5, 50, 56, 54],
           [6, 60, 67, 43],
           [7, 70, 78, 32],
           [8, 80, 89, 21],
           [9, 90, 90, 12],
           [0, 100, 111, 23]])

total=A@B
print(total)

[[   165   1650   1850   3092]
 [  3090 154000 170225  48349]
 [ 24191 265310 295061 199071]]


Data frame (index * columns): Matrix  
Series: Vector

In [14]:
import pandas as pd
from sklearn. datasets import load_breast_cancer
breast_cancer = load_breast_cancer()
breast_cancer_df = pd.DataFrame(data = 
breast_cancer.data, columns = breast_cancer.feature_names)
breast_cancer_df['label'] = breast_cancer.target
breast_cancer_df

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                   0.07871  ...          17.33           184.60      2019.0   
1                   0.05667  ...          23.41           158.80      1956.0   
2                   0.05999  ...          25.53           152.50      1709.0   
3                   0.09744  ...          26.50            98.87       567.7   
4                   0.05883  ...          16.67           152.20      1575.0   
..                      ...  ...            ...              ...         ...   
564                 0.05623  ...          26.40           166.10      2027.0   
565                 0.05533  ...          38.25           155.00      1731.0   
566                 0.05648  ...          34.12           126.70      1124.0   
567                 0.07016  ...          39.42           184.60      1821.0   
568                 0.05884  ...          30.37            59.16       268.6   

     worst smoothness  worst compactness  worst concavity  \
0             0.16220            0.66560           0.7119   
1             0.12380            0.18660           0.2416   
2             0.14440            0.42450           0.4504   
3             0.20980            0.86630           0.6869   
4             0.13740            0.20500           0.4000   
..                ...                ...              ...   
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     worst concave points  worst symmetry  worst fractal dimension  label  
0                  0.2654          0.4601                  0.11890      0  
1                  0.1860          0.2750                  0.08902      0  
2                  0.2430          0.3613                  0.08758      0  
3                  0.2575          0.6638                  0.17300      0  
4                  0.1625          0.2364                  0.07678   

In [15]:
breast_cancer_df['label'].value_counts()

1    357
0    212
Name: label, dtype: int64

In [17]:
breast_cancer_df['worst radius'].mean()

16.269189806678387

In [18]:
breast_cancer_df['worst symmetry'].sum()

165.053